### ISSUE TITLE
Cannot sendImage [WAUTH-2 and WA 1.5 ]

### ISSUE THREAD

**Issue by hungchai** [hidespb/node-whatsapi#29]
I tried [WAUTH-2 and WA 1.5] to send image message, but it throw exception. Anyone can advise it?
This is my debug message.
```
Connected to WA Server

tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>

tx <auth mechanism="WAUTH-2" user="852xxxxxxx">104 data length</auth>

rx <start from="s.whatsapp.net"></start>

rx <stream:features></stream:features>

rx <challenge>20 data length</challenge>

tx <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">35 data length</response>

rx <success t="1421589322" props="4" kind="free" status="active" creation="1417702829" expiration="1449238829">20 data length</success>
Logged in to WA Server

tx <presence name="TOM"></presence>

rx <ib from="s.whatsapp.net">
rx   <offline count="0"></offline>
rx </ib>

rx <presence from="852xxxxxxx@s.whatsapp.net"></presence>

tx <iq id="[message-1443256747-1]" to="s.whatsapp.net" type="set" xmlns="w:m">
tx   <media hash="dx16x09AvKVb7i6igvrD6Q6xGnKfbPV5Rc3iVVmLfEM=" type="image" size="77470"></media>
tx </iq>

rx <iq from="s.whatsapp.net" id="[message-1443256747-1]" type="result">
rx   <media url="https://mmi221.whatsapp.net/u/vJw9-2aoY1XRJ_y-ukjy0r74cH4ABQztjrl85g/AgUdVEsxE53X58aQfIL5GiCuEcQr-R9KSMu9wNPXybJO" ip="198.23.87.77"></media>
rx </iq>

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
```

**Comment by tvandergeer** [comment]
Can you subscribe to the "error" event and print out the results?

```
wa.on('error', function(){
   console.log("Error event: ", arguments[0]); 
});
```

**Comment by hungchai** [comment]
```
Error event:  { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

**Comment by tvandergeer** [comment]
Search for this error on Google. Do you happen to be running into this situation:

  *"By default, node throws EPIPE errors if process.stdout is being written to and a user runs it through a pipe that gets closed while the process is still outputting (eg, the simple case of piping a node app through head)."*

[Source + possible solution](https://github.com/mhart/epipebomb)

**Comment by tvandergeer** [comment]
Are you running Node as a background process to send images via WhatsApp?

**Comment by hungchai** [comment]
No, I run the js in webstorm, I am not sure this is the cause or not.

**Comment by matteocontrini** [comment]
Can you try running it in the "classic" way, using a terminal and typing "node app.js"?

**Comment by hungchai** [comment]
tried, but show same error message

**Comment by hungchai** [comment]
This is my app.js
```
var common = require('./node-whatsapi');
var events = require('events');
var util = require('util');

var defaultConfig = {
    msisdn         : '8525907878',
    device_id      : '%17%b2%ba%9b%f5%f5%18%8b%6e%39%0e%14%ea%88%82%65',
    username       : 'TOM',
    password       : '',
    ccode          : '852',
    reconnect      : true,
    host           : 'c.whatsapp.net',
    server         : 's.whatsapp.net',
    gserver        : 'g.us',
    port           : 443,
    device_type    : 'Android',
    app_version    : '2.11.473',
    ua             : 'WhatsApp/2.11.473 Android/4.3 Device/GalaxyS3',
    challenge_file : __dirname + '/node-whatsapi/challenge'
};


var wa = new common.createAdapter(defaultConfig,true);
util.inherits(wa, events.EventEmitter);

wa.connect();
wa.on('error', function(){
    console.log("Error event: ", arguments[0]);
});
//Wait for connection event and the login to WA Server
wa.on('connect', function(){
    console.log("Connected to WA Server");
    wa.login(); 
});

//Wait for Login event
wa.on('login', function(){
    console.log("Logged in to WA Server");
    //TODO: send composing/paused status
    wa.sendIsOnline();
    wa.sendImage("85260105346", 'http://lorempixel.com/800/600/?.jpg', 'This is a caption', '[message-1443256747-1]');
   
});



wa.on('message.delivered', function(from, id, t){
   console.log("Message received by:"+from);
   //wa.disconnect();  //WA server connection will be disconnected
});

//Receive typing status
wa.on('typing', function(from, tag){
    console.log(from+"-"+tag);
}); 

//Event to receive and log messages
wa.on('message', function(from, id, name, body, author){
   console.log("Message: "+body+" From: "+from+" Name: "+name);
});

```

**Comment by viniciusgalvao** [comment]
@hungchai Take a test. In place of the image link try to send a picture that is on your local project.

**Comment by hungchai** [comment]
@viniciusgalvao, Thanks for your reply. The Image file existed under /Media folder that copied from the link by the program.

**Comment by viniciusgalvao** [comment]
@hungchai I had a similar problem, but it was while building the thumbnail. The imagemagick was not working on my machine and it generated an exception when sending the image.

**Comment by tvandergeer** [comment]
Thanks for reporting. It should be fixed with this commit: 853790731b68934300462c63ea6b7a86fd0fc808
Can you please verify?

NB. The EPIPE error is most likely caused by the way you run your node app. It's not a problem in node-whatsapi

**Comment by hungchai** [comment]
Do I need to install imagemagick lib to my OS X?

**Comment by matteocontrini** [comment]
No, it's included as a Node module in node-whatsapi. Make sure you have all the dependencies installed running npm install in the WhatsAPI folder

**Comment by hungchai** [comment]
After I reinstall imagemagick to my mac, the exception is gone, but it still cannot receive image
```
tx <iq id="upload-1421853441-1" to="s.whatsapp.net" type="set" xmlns="w:m">
tx   <media hash="zspqa807w2GZyqfh8pAqCOnTV6SrouPADirc3rRhtyg=" type="image" size="57165"></media>
tx </iq>

rx <iq from="s.whatsapp.net" id="upload-1421853441-1" type="result">
rx   <media url="https://mmi617.whatsapp.net/u/KuAMa766-ua1Pz3ZGF4_1E4IdCAABQ0rDUZJjQ/Asvi67CPmsGYzAdccBW0Sro_X3vNOvsXaeyS9Dhl-k-i" ip="184.173.204.41"></media>
rx </iq>

tx <message to="852xxxxxxx@s.whatsapp.net" type="text" id="message-1421853442-2" t="1421853442">
tx   <media xmlns="urn:xmpp:whatsapp:mms" caption="This is a caption" url="https://mmi617.whatsapp.net/d/Asvi67CPmsGYzAdccBW0Sro_X3vNOvsXaeyS9Dhl-k-i.jpg" type="image" size="57165" file="49f3e75b25bb250dc8fa3bcc123d95c8.jpeg">2652 data length</media>
tx </message>

rx <ack from="852xxxxxxx@s.whatsapp.net" id="message-1421853442-2" class="message" t="1421853442"></ack>
```

**Comment by matteocontrini** [comment]
Is that using the latest commit?

--
Matteo
Inviato da Windows Phone

----- Messaggio originale -----
Da: "hungchai" <notifications@github.com>
Inviato: ‎21/‎01/‎2015 16:19
A: "hidespb/node-whatsapi" <node-whatsapi@noreply.github.com>
Cc: "Matteo Contrini" <m.contrini@gmail.com>
Oggetto: Re: [node-whatsapi] Cannot sendImage [WAUTH-2 and WA 1.5 ] (#29)

After I reinstall imagemagick to my mac, the exception is gone, but it still cannot receive image
tx <iq id="upload-1421853441-1" to="s.whatsapp.net" type="set" xmlns="w:m">
tx   <media hash="zspqa807w2GZyqfh8pAqCOnTV6SrouPADirc3rRhtyg=" type="image" size="57165"></media>
tx </iq>

rx <iq from="s.whatsapp.net" id="upload-1421853441-1" type="result">
rx   <media url="https://mmi617.whatsapp.net/u/KuAMa766-ua1Pz3ZGF4_1E4IdCAABQ0rDUZJjQ/Asvi67CPmsGYzAdccBW0Sro_X3vNOvsXaeyS9Dhl-k-i" ip="184.173.204.41"></media>
rx </iq>

tx <message to="852xxxxxxx@s.whatsapp.net" type="text" id="message-1421853442-2" t="1421853442">
tx   <media xmlns="urn:xmpp:whatsapp:mms" caption="This is a caption" url="https://mmi617.whatsapp.net/d/Asvi67CPmsGYzAdccBW0Sro_X3vNOvsXaeyS9Dhl-k-i.jpg" type="image" size="57165" file="49f3e75b25bb250dc8fa3bcc123d95c8.jpeg">2652 data length</media>
tx </message>

rx <ack from="852xxxxxxx@s.whatsapp.net" id="message-1421853442-2" class="message" t="1421853442"></ack>

**Comment by viniciusgalvao** [comment]
@hungchai  This your last problem was resolved with the latest commit 8537907 made by @tvandergeer

**Comment by hungchai** [comment]
@tvandergeer, @viniciusgalvao
Thanks, actually, I am using late week commit. I will retry this func again with the latest commit.

**Comment by hungchai** [comment]
Thanks, it works
